version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: cassproject
    versions:
    - 3.1.7
    - 3.1.8
    - 3.1.9
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: vuepress
    versions:
    - 1.8.0
    - 1.8.1
    - 1.8.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@vuepress/core"
    versions:
    - 1.8.0
    - 1.8.1
    - 1.8.2
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: dateformat
    versions:
    - 4.5.0
    - 4.5.1
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
