name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: git pull --recurse-submodules
      - run: git submodule update --init --remote
      - run: export VUE_APP_API_LOGIN_ENABLED=false
      - run: npm ci
      - run: npm run docs:build
      - run: find public/docs -type f -exec sed -i "s/\/docs/..\/../g" {} \;
      - run: find public/docs/assets/css -type f -exec sed -i "s/\/docs//g" {} \;
      - run: find public/docs/assets/js -type f -exec sed -i "s/..\/..\/docs/\/docs/g" {} \;
      - run: sed -i "s/\/..\//\//g" ./public/docs/index.html
      - run: npm run build
      
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
